# Generated by Django 4.1.1 on 2022-10-11 09:00

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articles',
            options={'verbose_name': 'Посты', 'verbose_name_plural': 'Посты'},
        ),
        migrations.AlterField(
            model_name='articles',
            name='full_text',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
